---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: umbra
# description will be included in the image's metadata
description: The future is darker than you think.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: dnf.yml
  - from-file: flatpak.yml

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    snippets:
      - "rm -rf /usr/share/applications/Waydroid"
      - "rm -f /usr/share/applications/bazzite-documentation.desktop"
      - "rm -f /usr/share/applications/bazzite-steam-bpm.desktop"
      - "rm -f /usr/share/applications/bbrew.desktop"
      - "rm -f /usr/share/applications/discourse.desktop"
      - "rm -f /usr/share/applications/system-update.desktop"
      - "rm -f /usr/share/applications/waydroid-container-restart.desktop"
      - "rm -f /usr/libexec/waydroid-container-restart"
      - "rm -f /usr/libexec/waydroid-container-start"
      - "rm -f /usr/libexec/waydroid-container-stop"
      - "rm -f /usr/libexec/waydroid-fix-controllers"
      - "rm -f /usr/share/containers/systemd/cockpit-container.container"
      - "rm -f /etc/xdg/autostart/bazzite-announcement.desktop"

  - type: os-release
    properties:
      ID: umbra
      NAME: Umbra
      PRETTY_NAME: Umbra

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
