#ARG BASE_IMAGE=kinoite-main
#FROM ghcr.io/ublue-os/${BASE_IMAGE}:latest
#FROM quay.io/fedora-ostree-desktops/kinoite:41
FROM ghcr.io/alxhr0/horizon-base:latest

COPY scripts/shared/build.sh /tmp/shared-build.sh
COPY editions/kinoite/build.sh /tmp/build.sh

COPY files/shared /
COPY files/kinoite /

RUN mkdir -p /var/lib/alternatives && \
    echo "kinoite" >> /usr/share/umbra/image_type && \
    /tmp/shared-build.sh && \
    /tmp/build.sh && \
    ostree container commit
