#!/usr/bin/env bash

image_type=$(cat /usr/share/umbra/image_type)

if grep -q "plasma" /usr/share/umbra/image_type; then
    konsoleprofile ColorScheme='Ashy Decay'
    plasma-apply-colorscheme AshyDecay
    plasma-apply-wallpaperimage /usr/share/umbra/wallpapers/tux.jpg
fi

systemctl disable --user umbra-flatpak-manager.service
