#!/usr/bin/env bash

image_type=$(cat /usr/share/nova/image_type)

if grep -q "plasma" /usr/share/umbra/image_type; then
    konsoleprofile ColorScheme='Ashy Decay'
    plasma-apply-colorscheme AshyDecay
fi

rm /etc/xdg/autostart/umbra-theme-manager.desktop
