#!/usr/bin/env bash


# Ensure Flathub is enabled
#flatpak remote-add --if-not-exists --system flathub /etc/flatpak/remotes.d/flathub.flatpakrepo
flatpak remote-add --if-not-exists --system flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify --system --enable flathub

flatpak remote-delete fedora -y


# Flatpak theming support
flatpak override \
  --filesystem=xdg-config/gtk-4.0:ro \
  --filesystem=xdg-config/gtk-3.0:ro \
  --filesystem=xdg-data/icons:ro

# XInput for Firefox
flatpak override \
  --system \
  --env=MOZ_USE_XINPUT2=1 \
  org.mozilla.firefox

# Fix printing on LibreOffice
flatpak override \
  --system \
  --socket=cups \
  --socket=session-bus \
  org.libreoffice.LibreOffice

# Allow MangoHUD config for Flatpaks
flatpak override \
  --filesystem=xdg-config/MangoHud:ro \
  --filesystem=xdg-config/vkBasalt:ro

# Fix permissions for XIV Launcher
flatpak override \
  --device=dri \
  dev.goats.xivlauncher

# Fix permissions for Protontricks
flatpak override \
  --filesystem=~/.local/share/Steam \
  --filesystem=/var/mnt \
  --filesystem=/run/media \
  com.github.Matoking.protontricks

# Params needed for HW accelerated video on Nvidia (Ignoring hybrid systems)
if [[ $IMAGE_FLAVOR =~ "nvidia" ]] && [ $(grep -o "\-display" <<< $(lshw -C display) | wc -l) -le 1 ] && grep -q "vendor: NVIDIA Corporation" <<< $(lshw -C display); then
  flatpak override \
    --system \
    --filesystem=host-os \
    --env=LIBVA_DRIVER_NAME=nvidia \
    --env=LIBVA_DRIVERS_PATH=/run/host/usr/lib64/dri \
    --env=LIBVA_MESSAGING_LEVEL=1 \
    --env=MOZ_DISABLE_RDD_SANDBOX=1 \
    --env=NVD_BACKEND=direct \
    org.mozilla.firefox
else
  # Undo if user was previously using a Nvidia image and is no longer
  flatpak override \
    --system \
    --nofilesystem=host-os \
    --unset-env=LIBVA_DRIVER_NAME \
    --unset-env=LIBVA_DRIVERS_PATH \
    --unset-env=LIBVA_MESSAGING_LEVEL \
    --unset-env=MOZ_DISABLE_RDD_SANDBOX \
    --unset-env=NVD_BACKEND \
    org.mozilla.firefox
fi

xargs -a /usr/share/umbra/packages/flatpaks flatpak install flathub  --system -y

if grep -q "plasma" /usr/share/umbra/image_type; then
  flatpaks_to_remove="/usr/share/umbra/plasma/packages/flatpaks_remove"

  while IFS= read -r app; do
      if flatpak list --app | awk '{print $1}' | grep -qx "$app"; then
          echo "Removing $app..."
          flatpak remove -y --system "$app"
      else
          echo "$app is not installed, skipping..."
      fi
  done < "$flatpaks_to_remove"
elif grep -q "niri" /usr/share/umbra/image_name; then
    xargs -a /usr/share/umbra/niri/packages/flatpaks flatpak install flathub  --system -y
fi

systemctl disable --now umbra-flatpak-manager.service
