set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    source /usr/lib/ujust/libformatting.sh
    #/usr/bin/just --justfile justfile --list --list-heading $'Available commands:\n' --list-prefix $' - '
    /usr/bin/just --justfile /usr/share/umbra/cast/justfile $1



# Imports
import "./justfiles/00-default.just"
import "./justfiles/10-fixes.just"
import "./justfiles/20-programming.just"
