#ARG BASE_IMAGE=kinoite-main
#FROM ghcr.io/ublue-os/${BASE_IMAGE}:latest
#FROM quay.io/fedora-ostree-desktops/kinoite:41
FROM quay.io/fedora/fedora-bootc:latest

COPY scripts/shared/build.sh /tmp/shared-build.sh
COPY editions/plasma/build.sh /tmp/build.sh

COPY files/shared /
COPY files/plasma /

RUN mkdir -p /var/lib/alternatives && \
    /tmp/shared-build.sh && \
    /tmp/build.sh && \
    echo "plasma" >> /usr/share/umbra/image_type && \
    ostree container commit
